name: age_predictor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'

dependencies:
  assets: ^0.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  http: ^1.1.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
